name: Notify Discord on Push and Issue Opened

on:
  push:
    branches:
      - main
  issues:
    types: [opened]

jobs:
  notify-discord-push:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord for push
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"content\": \"New commit pushed: ${{ github.event.head_commit.message }}\"}" \
        https://discordapp.com/api/webhooks/YOUR_WEBHOOK_URL

  notify-discord-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord for new issue
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"content\": \"Nueva issue abierta por ${{ github.actor }}: ${{ github.event.issue.title }}. Ver detalles aquí: ${{ github.event.issue.html_url }}\"}" \
        https://discord.com/api/webhooks/1294780729556996117/u6BnnAlSUvQxfd86e2dsYAz-bVmb7yyrednL_6jqeISUS2BrzdVgL7nF3IpzMYcF_-ER
