name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"content\": \"New update on GitHub repository: ${{ github.event.head_commit.message }}\"}" \
        https://discord.com/api/webhooks/1294780729556996117/u6BnnAlSUvQxfd86e2dsYAz-bVmb7yyrednL_6jqeISUS2BrzdVgL7nF3IpzMYcF_-ER
