name: Notify Discord on Issue Opened

on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"content\": \"Nueva issue abierta por ${{ github.actor }}: ${{ github.event.issue.title }}. Ver detalles aquí: ${{ github.event.issue.html_url }}\"}" \
        https://discord.com/api/webhooks/1294780729556996117/u6BnnAlSUvQxfd86e2dsYAz-bVmb7yyrednL_6jqeISUS2BrzdVgL7nF3IpzMYcF_-ER
